### ISSUE TITLE
Automatic generation of images of spatial or matrix data

### ISSUE THREAD

**Issue by idavies-anu** [3worlds/3w#3]
When running experiments we need facility for automatic generation of images from each simulation for the purpose of experiment documentation.
This is urgent for publications. The only way at the moment is to run treatments individually and screen capture widget outputs!
Probably png files unless preserving resolution with resizing then may have to be svg. I note that the flowChart.svg files are very slow to resize.

**Comment by 3worlds** [comment]
For output re-use for analyses (eg image analysis with R or ImageJ, integration to GIS, etc.) it may be better so save maps as `.tiff` or some other format with loseless compression rather than `jpeg/png`.

**Comment by idavies-anu** [comment]
This facility has now been added to the next release.
